---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /netbox
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "docker"
    groups:
      docker:
        patterns:
          - "*"
