# Multi-arch build definition: Supervisor automatically injects BUILD_FROM per architecture,
# so we only need to declare the mapping once here.
build_from:
  \1v4.4.6-3.4.2
  \1v4.4.6-3.4.2
# OCI labels surface metadata in ghcr.io and the Supervisor UI.
labels:
  "org.opencontainers.image.title": "NetBox Home Assistant Add-on"
  "org.opencontainers.image.source": "https://github.com/boecht/ha-addon-netbox"
  "org.opencontainers.image.licenses": "Apache-2.0"
